### PR TITLE
Accept cosigner tokens from input.

### PR DESCRIPTION
**Pull request by nodar-chkuaselidze**
With this PR creating and joining wallet will require cosignerToken as an input with the same requirements as it was before: `32 byte buffer`.

Notes:
 This will move responsibility of generating tokens to the users, server will just store them in the database, instead of generating them and providing to the users.
 This will allow users to have any scheme to derive their tokens, we can make it more flexible by accepting variable size buffers later. But for the next batch we might consider using signing schemes for authentication (which has its own downsides, e.g. you will have to decrypt your private key to do a request if you are not using Hardware wallet) - other PubKey based authentication system (e.g. webauthn with u2f fallback).

This PR includes:
- [x] Move client to bmultisig-client
- [x] fix couple routes with req.cosigner (Admin client would have caused errors.)
- [x] Accept cosigner tokens from users.

### CODE REVIEW

**Comment by nodar-chkuaselidze** [comment]
Changes in bmultisig-client: https://github.com/bcoin-org/bmultisig-client/pull/3

**Comment by tynes** [comment]
Pulled down locally and am testing by passing my own tokens. Works so far as expected

**Comment by tynes** [comment]
Are you done actively developing this branch? I can review it if so

**Comment by nodar-chkuaselidze** [comment]
Yes, this was ready. I thought you were testing it :)

**Pull request merged**
