### PR TITLE
Match APIs to bwallet.

### PR DESCRIPTION
**Pull request by nodar-chkuaselidze**
_Note: notes below may not match the pushed code while its WIP_

### Resolve this.
Account:
  - [x] do we omit author key in account.toJSON() to be compatible with wallet

Wallet:
  - [x] wallet.toJSON returning `master: null` makes more
  sense for multisig wallets (master does not do a thing).
  This PR will return `{ encrypted: false }` for `master` to be compatible, even
  though it does nothing.

### Notes

Account notes:
  1. watchOnly is always true.
  2. account.type is always `multisig`
  3. account.indexPath does not make sense in bmultisig context.
    3.1. But we can store indexPath for each XPUB that we receive.
    3.2. account.accountKey is just author of the multisig wallet, do we
      returning to the output only for compatibility.
    3.3. account.toJSON().keys -- will actually include accountKey as well,
    that's deviation from the bwallet.

WalletDB Notes:
  - WalletDB even though accepts `name` for the account, it will still
  use `default` for account name. (bug in walletdb._createAccount)

Wallet Notes:
  1. Wallet does not have `token` and `tokenDepth`.
  Authentication model in bmultisig is based on cosigner tokens and
  if we switch authentication from current bmultisig generated tokens
  to received from users, tokenDepth wont exist as well.
  2. Wallet does not have `master`.
  3. Deprecate `details` on getInfo, only return `wallet`.

HTTP Notes:
  - Wallet creation and walet getInfo don't include account
  - Account call has been separated.

### CODE REVIEW

**Comment by tynes** [comment]
I think having additional fields is ok as long as it has all of the wallet fields that currently exist as well

**Comment by tynes** [comment]
Join wallet should update `xpub` to `accountKey`

https://github.com/bcoin-org/bmultisig/pull/41/files#diff-1c0f1c434b17b7f8795d44a51a14320aL351

**Comment by nodar-chkuaselidze** [comment]
Do we want to target bcoin master on this master?

I can leave bcoin dependency from github, but I wanted to avoid it by all means. That's the reason I have not tested it against master. :)

**Comment by tynes** [comment]
I would prefer to target bcoin master because hardware signing requires the `createTX` endpoint to work with `sign: false` so that it returns an unsigned tx to the client. This feature is not on bcoin master

**Comment by nodar-chkuaselidze** [comment]
I guess omitting wallet authors key from `keys` makes compatible with bcoin wallet and that's is pretty big change from API consumers. I will omit authors key from `keys` (It can be found in accountKey as for bcoin wallet)

**Comment by tynes** [comment]
Consuming the API, it feels awkward sometimes when I have to pass the token as both `token` and as `cosignerToken`

Here it authenticates using `token` to attach the cosigner to the request body
https://github.com/nodar-chkuaselidze/bmultisig/blob/43f59c92dd40f1af291149349201535bedb98ee5/lib/http.js#L169

Here it builds the cosigner using `cosignerToken`
https://github.com/nodar-chkuaselidze/bmultisig/blob/43f59c92dd40f1af291149349201535bedb98ee5/lib/http.js#L343

It would be more ideal if these 2 were combined into a single value so that we can have a unified API. Then in the docs we could recommend creating a new `MultisigClient.wallet` for each cosigner like so:

```js
const client = new MultisigClient({...})
const wallet = client.wallet('wallet-id', 'cosigner-token')
```

Then the methods wouldn't have to include `cosignerToken` in the post body and would be able to just use the `token` that is already required since its being used in the auth middleware

**Comment by tynes** [comment]
https://github.com/nodar-chkuaselidze/bmultisig/blob/43f59c92dd40f1af291149349201535bedb98ee5/lib/http.js#L533

This line will send the scripts over the wire as a serialized buffer object.

`scripts.map(s => s.toRaw('hex'))` turns them into Buffers, on the client side each script is received as `{type: 'Buffer', data: uint8[]}`, these objects still work fine in `Buffer.from` but I am wondering what you think about doing something like `scripts.map(s => s.toRaw('hex')).toString('hex')` instead so that they are sent over the wire as string literals

**Comment by nodar-chkuaselidze** [comment]
`token` will be used for wallet creation and joining,
`newToken` will be used when you want to change token.

About toString('hex'), yeah it changed in bcoin. previously if you used toRaw('hex') it would return hex string. But with this it should be compatible with both.

**Comment by tynes** [comment]
>`token` will be used for wallet creation and joining,
> `newToken` will be used when you want to change token.

I'm not sure I understand what you mean here. Is this a proposed change?

> About toString('hex'), yeah it changed in bcoin. previously if you used toRaw('hex') it would return hex string. But with this it should be compatible with both.

You can call `toString` on a string and it will return a string, so calling `toString` will be compatible with both and will always return a string if using bcoin#master or bcoin@1.0.2

**Comment by nodar-chkuaselidze** [comment]
They are the changes I made with last commits.

**Pull request merged**
